stages:
  - deploy

# common script to add deploy keys
.prepare_image_for_deploy: &deploy_before_script
  image: docker-registry.sabay.com/docker/ssh-deploy
  before_script:
    - mkdir -p ~/.ssh || true
    - eval $(ssh-agent -s)
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo -e "$DEPLOY_KEY\n" > ~/.ssh/key
    - chmod 600 ~/.ssh/key
    - ssh-add ~/.ssh/key

# deploy to staging server for master testing before release
app_deploy_master:
  <<: *deploy_before_script
  variables:
    TARGET: gitlab@103.237.53.71
    DEPLOY_KEY: ${DEPLOY_TEST_KEY}
    DEPLOY_DIR: /srv/docker/${CI_ENVIRONMENT_NAME}/${CI_PROJECT_NAME}
  stage: deploy
  script:
    - make deploy
  environment:
    name: master
    url: https://kpi.master.sabay.com
  only:
    - master
  tags:
    - docker

# deploy to testing
app_deploy_testing:
  <<: *deploy_before_script
  variables:
    TARGET: gitlab@103.237.53.72
    DEPLOY_KEY: ${DEPLOY_TEST_KEY}
    DEPLOY_DIR: /srv/docker/${CI_ENVIRONMENT_NAME}/${CI_PROJECT_NAME}
  stage: deploy
  script:
    - make deploy
  environment:
    name: testing
    url: https://kpi.testing.sabay.com
  only:
    - tags
  tags:
    - docker
