version: "2"
services:
  mongo:
    image: docker-registry.sabay.com/docker/mongodb:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./mongo/data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    networks:
      - sabay_docker

  mongo-rs0-1:
    image: docker-registry.sabay.com/docker/mongodb:latest
    container_name: mongodb2
    hostname: mongodb2
    ports:
      - 27018:27017
    volumes:
      - ./mongo-rs-1/data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    networks:
      - sabay_docker

  mongo-rs0-2:
    image: docker-registry.sabay.com/docker/mongodb:latest
    container_name: mongodb3
    hostname: mongodb3
    ports:
      - 27019:27017
    volumes:
      - ./mongo-rs-2/data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    networks:
      - sabay_docker

networks:
  sabay_docker:
    external: true
