version: '3.5'
services:
  mosquitto:
    container_name: mosquitto
    hostname: localhost
    image: eclipse-mosquitto:1.6.14
    restart: always
    ports:
       - "1883:1883"
       - "9001:9001"
networks:
  webnet:
    external: true